
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Hytmng\PhpShell\Command\:
        resource: '../src/PhpShell/Command/*'
        exclude:
            - '../src/PhpShell/Command/CommandResults.php'
            - '../src/PhpShell/Command/Command.php'
        tags: ['console.command']

    Hytmng\PhpShell\Prompt\Provider\:
        resource: '../src/PhpShell/Prompt/Provider/*'
        exclude: '../src/PhpShell/Prompt/Provider/VariableProviderInterface.php'
        tags: ['console.prompt.variable_provider']
